spring.application.name=fullstackSpringBoot
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.qtlteybwmdwlmlzwoiaf
spring.datasource.password=r!*#&4U8_7#&drN

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

spring.secretkey=WebDauGiaByThinhIT137

spring.accesstoken-token-expiration=15m
spring.refresh-token-expiration=7d

spring.mail.host=smtp@gmail.com
spring.mail.port=587
spring.mail.username=baitaplon13072005@gmail.com
spring.mail.password=dfoppbaeopzkbqwd
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.nextjs.link=http://localhost:3000